### ISSUE TITLE
proxmark3-flasher not actually included?

### ISSUE THREAD

**Issue by victorhooi** [RfidResearchGroup/homebrew-proxmark3#10]
The README mentions that proxmark3-flasher should be included.

However, I have just run:

```
brew install --HEAD proxmark3
```

and proxmark3-flasher does not appear to be compiled/installed.
```
bash-3.2$ proxmark3-flasher
bash: proxmark3-flasher: command not found
```

Are there separate steps required for it?

[output_brew_ls_verbose_proxmark3.txt](https://github.com/RfidResearchGroup/homebrew-proxmark3/files/3856042/output_brew_ls_verbose_proxmark3.txt)

**Comment by doegox** [comment]
instructions were not updated, thanks for your report.
It's now fixed.
