### ISSUE TITLE
Firmware path in README appears to be incorrect

### ISSUE THREAD

**Issue by victorhooi** [RfidResearchGroup/homebrew-proxmark3#12]
The README refers to the firmware being at:

However, from what I can tell, the firmware is actually at `/usr/local/Cellar/proxmark3/HEAD-<ID>/share/proxmark3/firmware/`:
```
bash-3.2$ cd /usr/local/Cellar/proxmark3/HEAD-f08fd01/share/proxmark3/firmware/
bash-3.2$ ls
bootrom.elf		fullimage.elf		proxmark3_recovery.bin	sim011.bin		sim011.sha512.txt
```

Do you want me to put a PR for the README?

**Comment by doegox** [comment]
That's how homebrew is supposed to work.

**Comment by iceman1001** [comment]
I think @victorhooi is refering the readme document where the path to the firmware doesn't include the "head-id" part.    ie we documented for normal release,  but for -head install,  we didn't document that fw images will be one subfolder down in the hierarchy.

**Comment by doegox** [comment]
The README tells the firmware is located at `/usr/local/share/proxmark3/firmware` and that information is correct.
When a homebrew package is properly deployed, it's a symlink to the Cellar:
![Screenshot from 2019-11-18 10-59-39](https://user-images.githubusercontent.com/60773/69043191-e19b2c00-09f2-11ea-9938-f009daafd392.png)

The example above is with a `install --HEAD`.
So I don't see what's wrong in the doc and I don't understand your following change @iceman1001 
```diff
@@ -38,6 +39,9 @@ Proxmark3 client will be installed in
 Firmware will be located in 
 `/usr/local/share/firmware/`  
 
+_If you did a **install --HEAD**,  the firmware will be located in a subfolder_
```

**Comment by iceman1001** [comment]
It was a blind shot in trying to make it more clear. Didn't know the stuff go symlinked.  I still don't use OS X.

**Comment by doegox** [comment]
ok I updated the readme to clarify it
