### ISSUE TITLE
BigBuf.h:42:1: error: target attribute is not supported on this machine

### ISSUE THREAD

**Issue by mateuspestana** [RfidResearchGroup/homebrew-proxmark3#16]
Hello guys! 

So, I've installed PM3 on my Mac OS X 10.15.5 (Macbook Pro 2019 15") using Brew, and everything is working perfectly. My last working version is from commit bcb0e5d. I'm trying to update it to the last unstable version for a few weeks, but everytime I try so (using brew upgrade --fetch-HEAD proxmark3) I get the following: 

```Last 15 lines from /Users/mateuspestana/Library/Logs/Homebrew/proxmark3/02.make:
[=] LD fpga_compress
[*] MAKE armsrc/all
compiler version:  arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 5.4.1 20160919 (release) [ARM/embedded-5-branch revision 240496]
[-] GEN fpga_version_info.c
[-] CC fpga_version_info.c
[-] GEN obj/fpga_all.bit.z
[-] GEN obj/fpga_all.o
[-] CC start.c
In file included from start.c:18:0:
BigBuf.h:42:1: error: target attribute is not supported on this machine [-Werror=attributes]
 bool RAMFUNC LogTrace(const uint8_t *btBytes, uint16_t iLen, uint32_t timestamp_start, uint32_t timestamp_end, uint8_t *parity, bool readerToTag);
 ^
cc1: all warnings being treated as errors
make[1]: *** [obj/start.o] Error 1
make: *** [armsrc/all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/RfidResearchGroup/homebrew-proxmark3/issues`

==> Checking for dependents of upgraded formulae...
==> No dependents found!
```

At first I thought it was something with that commit/version, but it is persistent and every one I try since then. 

Any thoughts on this?

**Comment by iceman1001** [comment]
Your arm-non-eabi-gcc build chain is out-of-date.   If you reinstall the proxmark brew,  it should install a later one.

`brew install RfidResearchGroup/proxmark3/arm-none-eabi-gcc`

**Comment by mateuspestana** [comment]
Oh, thank you! Worked like a charm.
