### ISSUE TITLE
brew fails to compile current version firmware

### ISSUE THREAD

**Issue by tengelmeier** [RfidResearchGroup/homebrew-proxmark3#20]
Hi, 

brew fails to compile the firmware of the current version: 

`

        rfidresearchgroup/proxmark3/proxmark3 HEAD-df17057 -> HEAD-df17057
        ==> Upgrading rfidresearchgroup/proxmark3/proxmark3 HEAD-df17057 -> HEAD-df17057 
        ==> Cloning https://github.com/RfidResearchGroup/proxmark3.git
        Updating /Users/te/Library/Caches/Homebrew/proxmark3--git
        ==> Checking out branch master
        Already on 'master'
        Your branch is up to date with 'origin/master'.
        HEAD is now at f96a48242 remake main screen text
        ==> make clean
        ==> make all PLATFORM=PM3RDV4 BREW_PREFIX=/usr/local
        Last 15 lines from /Users/te/Library/Logs/Homebrew/proxmark3/02.make:
        [=] LD fpga_compress
        [*] MAKE armsrc/all
        compiler version:  arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 5.4.1 20160919 (release) [ARM/embedded-5-branch revision 240496]
        [-] GEN fpga_version_info.c
        [-] CC fpga_version_info.c
        [-] GEN obj/fpga_all.bit.z
        [-] GEN obj/fpga_all.o
        [-] CC start.c
        In file included from start.c:20:0:
        bool RAMFUNC LogTrace(const uint8_t *btBytes, uint16_t iLen, uint32_t timestamp_start, uint32_t timestamp_end, uint8_t *parity, bool readerToTag);
        ^
       cc1: all warnings being treated as errors
       make[1]: *** [obj/start.o] Error 1
`

**Comment by iceman1001** [comment]
The arm-build chain needs to be updated.
```
brew remove proxmark3
brew reinstall proxmark3
``` 
Should install the new one for you.

**Comment by tengelmeier** [comment]
Thanks for the prompt reply. 

        brew remove proxmark3
        brew uninstall arm-none-eabi-gcc
        brew reinstall proxmark3

worked :-)
