### ISSUE TITLE
No rule to make target fpga_lf.bit', needed by fpga_version_info.c'

### ISSUE THREAD

**Issue by cybr1d** [RfidResearchGroup/homebrew-proxmark3#25]
Trying to install the iCopy-X platform.

I `brew edit proxmark3` and changed the generic platform.

`PLATFORM=#{build.with?('generic') ? 'PM3RDV4' : 'PM3RDV4'}`
into
`PLATFORM=#{build.with?('generic') ? 'PM3ICOPYX' : 'PM3RDV4'}`

and (re)install
`brew reinstall --with-generic proxmark3` 

Output:
```
==> Downloading https://github.com/RfidResearchGroup/proxmark3/archive/v4.14831.tar.gz
Already downloaded: /Users/cybr1d/Library/Caches/Homebrew/downloads/824da65008154df63f66b6fc317ac29f755287c1834bd1faf12eeb7d5952542d--proxmark3-4.14831.tar.gz
==> Reinstalling rfidresearchgroup/proxmark3/proxmark3 --with-generic
==> make clean
==> make all BREW_PREFIX=/usr/local PLATFORM=PM3ICOPYX
Last 15 lines from /Users/cybr1d/Library/Logs/Homebrew/proxmark3/02.make:
[-] CC flash-reset.s
[-] CC ../common_arm/usb_cdc.c
[-] CC ../common_arm/clocks.c
[-] CC bootrom.c
[=] LD obj/bootrom.elf
[=] GEN obj/bootrom.s19
[*] MAKE fpga_compress/all
[-] CC fpga_compress.c
[-] CC ../../common/lz4/lz4hc.c
[-] CC ../../common/lz4/lz4.c
[=] LD fpga_compress
[*] MAKE armsrc/all
compiler version:  arm-none-eabi-gcc (GNU Arm Embedded Toolchain 10-2020-q4-major) 10.2.1 20201103 (release)
make[1]: *** No rule to make target `fpga_lf.bit', needed by `fpga_version_info.c'.  Stop.
make: *** [armsrc/all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/rfidresearchgroup/homebrew-proxmark3/issues
```

Did I change the platform incorrectly?

**Comment by doegox** [comment]
Sorry, we forgot to provide the precompiled *.bit files for xc3s100e as by default they are ignored by git.
You can find them here:
https://github.com/RfidResearchGroup/proxmark3/tree/master/fpga-xc3s100e
These files will be part of future releases.

Note that the current icopyx Python frontend is *NOT* compatible with this proxmark3 client & firmware. So I hope you know what you are doing ;)
