### ISSUE TITLE
Tried to install with " --HEAD --with-blueshark proxmark3" options fails

### ISSUE THREAD

**Issue by star-bob** [RfidResearchGroup/homebrew-proxmark3#26]
Current install fails see below;

==> Cloning https://github.com/RfidResearchGroup/proxmark3.git
Updating /Users/mindphuq/Library/Caches/Homebrew/proxmark3--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 384e8eb4e Create codeql-analysis.yml
==> Installing proxmark3 from rfidresearchgroup/proxmark3
==> make clean
==> make all BREW_PREFIX=/usr/local PLATFORM=PM3RDV4 PLATFORM_EXTRAS=BTADDON
Last 15 lines from /Users/mindphuq/Library/Logs/Homebrew/proxmark3/02.make:
[-] CC ../../common/bucketsort.c
[-] CC iso14443crc.c
[-] CC sleep.c
[-] CC util_posix.c
[=] LD mf_nonce_brute
[-] CC mf_trace_brute.c
[=] LD mf_trace_brute
[*] MAKE mfd_aes_brute/all
[-] CC brute_key.c
[-] CC util_posix.c
[=] LD brute_key
ld: library not found for -lcrypto
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [brute_key] Error 1
make: *** [mfd_aes_brute/all] Error 2

**Comment by iceman1001** [comment]
interesting.

**Comment by iceman1001** [comment]
Pull latest,  it should be fixed
