### ISSUE TITLE
 icopy-x  ,  Capabilities structure version sent by Proxmark3 is not the same as the one used by the client!

### ISSUE THREAD

**Issue by lucyxss** [RfidResearchGroup/homebrew-proxmark3#28]
https://icopyx.com/

i try to install 
1 way .brew install proxmark3

2 way.export HOMEBREW_PROXMARK3_PLATFORM=PM3ICOPYX && brew install proxmark3

3 way.brew install --with-generic proxmark3

➜  ~ proxmark3 /dev/tty.usbmodem21101
[=] Session log /Users/lucy/.proxmark3/logs/log_20220215.txt
[+] loaded from JSON file /Users/lucy/.proxmark3/preferences.json
[=] Using UART port /dev/tty.usbmodem21101
[!!] 🚨 Capabilities structure version sent by Proxmark3 is not the same as the one used by the client!
[!!] 🚨 Please flash the Proxmark with the same version as the client.
[!!] 🚨 ERROR: cannot communicate with the Proxmark

➜  ~ uname -a
Darwin zxldeMacBook-Pro.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64

**Comment by iceman1001** [comment]
....  you would need to flash your device...

**Comment by doegox** [comment]
@lucyxss don't cross-post same issue across repos https://github.com/iCopy-X-Community/icopyx-teardown/issues/3
