### ISSUE TITLE
ICopy X support

### ISSUE THREAD

**Issue by SkyCZ** [RfidResearchGroup/homebrew-proxmark3#33]
Hi, 
Can you add --with-icopyx parameter to the brew (or something like that), to compile for icopy devices? [PM3ICOPYX](https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/md/Use_of_Proxmark/4_Advanced-compilation-parameters.md#platform)

**Comment by iceman1001** [comment]
feel free to contribute,  
this is a quite a stale repo.
