### ISSUE TITLE
Release v4.18340 is not reachable

### ISSUE THREAD

**Issue by hiwanz** [RfidResearchGroup/homebrew-proxmark3#43]
https://github.com/RfidResearchGroup/homebrew-proxmark3/blob/fad0a0709bace818a7f5b4ed8ca692cc1993134c/proxmark3.rb#L4 
==> Fetching rfidresearchgroup/proxmark3/proxmark3
==> Downloading https://github.com/RfidResearchGroup/proxmark3/archive/refs/tags/v4.18340.tar.gz
curl: (22) The requested URL returned error: 404

**Comment by iceman1001** [comment]
fixed
