### ISSUE TITLE
Impossible to upgrade from version 4.18218 to 4.18341 (macOS Sonoma 14.4 - 23E214)

### ISSUE THREAD

**Issue by Bricolas** [RfidResearchGroup/homebrew-proxmark3#46]
nicolas@iMac-de-Nicolas ~ % brew upgrade --greedy         
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################################### 100.0%
==> Upgrading 1 outdated package:
rfidresearchgroup/proxmark3/proxmark3 4.18218 -> 4.18341
==> Fetching rfidresearchgroup/proxmark3/proxmark3
==> Downloading https://github.com/RfidResearchGroup/proxmark3/archive/refs/tags/v4.18341.tar.gz
Already downloaded: /Users/nicolas/Library/Caches/Homebrew/downloads/7a4653b161290efc7e39118e8e740c30c3d1452442bd9306a681d88e1261eba2--proxmark3-4.18341.tar.gz
==> Upgrading rfidresearchgroup/proxmark3/proxmark3
  4.18218 -> 4.18341 --with-generi
==> make clean
==> make all BREW_PREFIX=/usr/local PLATFORM=PM3GENERIC
Last 15 lines from /Users/nicolas/Library/Logs/Homebrew/proxmark3/02.make:
      _Pm3PyRun_SimpleFileNoExit in cmdscript.o
      __wrap_delete_pm3 in pm3_pywrap.o
      __wrap_delete_pm3 in pm3_pywrap.o
      __wrap_pm3_name_get in pm3_pywrap.o
      __wrap_pm3_name_get in pm3_pywrap.o
      _pm3_swigregister in pm3_pywrap.o
      _pm3_swigregister in pm3_pywrap.o
      ...
  "__Py_NotImplementedStruct", referenced from:
      _SwigPyObject_richcompare in pm3_pywrap.o
      _SwigPyObject_richcompare in pm3_pywrap.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [proxmark3] Error 1
make: *** [client/all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/rfidresearchgroup/homebrew-proxmark3/issues

==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################################### 100.0%
nicolas@iMac-de-Nicolas ~ %

_iMac Retina 5K, 27-inch, 2017_

**Comment by jeremyforan** [comment]
I am getting the same issue.

**Comment by ninoyeman** [comment]
i  am getting the same issue. On mac mini m1

**Comment by cmsj** [comment]
FWIW, there is a workaround: https://github.com/RfidResearchGroup/proxmark3/issues/2305#issuecomment-1982762678

**Comment by Bricolas** [comment]
Fantastic !
Thank you, @cmsj !!
It is working fine.
In my case, I used next commands : 
```
brew unlink python
brew reinstall proxmark3 --with-generic
brew unlink python
```

**Comment by ninoyeman** [comment]
This worked for me too, thanks for the solution
