### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by Add3r** [RfidResearchGroup/homebrew-proxmark3#48]
==> Upgrading rfidresearchgroup/proxmark3/proxmark3
  4.17511 -> 4.18341 --with-generic
==> Downloading https://formulae.brew.sh/api/formula.jws.json

==> make clean
==> make all BREW_PREFIX=/opt/homebrew PLATFORM=PM3GENERIC
Last 15 lines from /Users/username/Library/Logs/Homebrew/proxmark3/02.make:
      _Pm3PyRun_SimpleFileNoExit in cmdscript.o
      __wrap_delete_pm3 in pm3_pywrap.o
      __wrap_pm3_name_get in pm3_pywrap.o
      _pm3_swigregister in pm3_pywrap.o
      _pm3_swiginit in pm3_pywrap.o
      _SWIG_Python_NewPointerObj in pm3_pywrap.o
      _SWIG_Python_ConvertPtrAndOwn in pm3_pywrap.o
      ...
  "__Py_NotImplementedStruct", referenced from:
      _SwigPyObject_richcompare in pm3_pywrap.o
      _SwigPyObject_richcompare in pm3_pywrap.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [proxmark3] Error 1
make: *** [client/all] Error 2

Test Machine: Macbook Pro M1 Sonoma 14.x

**Comment by iceman1001** [comment]
closing
