### ISSUE TITLE
hardnested tables moved

### ISSUE THREAD

**Issue by iceman1001** [RfidResearchGroup/homebrew-proxmark3#9]
We will need to update homebrew.
@merlokk  ?  hardnested tables is moved to resources

**Comment by doegox** [comment]
I fixed the paths in the formula.
But:
* non-bin subdirs stuffs are installed in bin/, imho they should go to share/
* these subdirs are not linked, neither the firmwares, I expected to find them linked in `brew --prefix`

**Comment by iceman1001** [comment]
I am not good at OS X and homebrew.    I tag some ppl and see if they can make it even better. @drandreas @tomharkness

**Comment by doegox** [comment]
alternative is to wait for the coming `make install` (with overridable install paths) that can avoid to duplicate the list of stuffs to move around...

**Comment by iceman1001** [comment]
And I see fw files end up in   `/usr/local/share/firmware/`
it should really be under 
`/usr/local/share/proxmark3/firmware/`

**Comment by doegox** [comment]
ouch yeah

**Comment by iceman1001** [comment]
Do we copy sim011, aswell?  ...

**Comment by doegox** [comment]
just see the full list at https://github.com/RfidResearchGroup/proxmark3/issues/325#issuecomment-523633394

**Comment by iceman1001** [comment]
ok,  moved stuff around.

However do we really need to copy this file into the emv folder anylonger?
```
    # do we need to copy this one to emv folder? (iceman)
    # emv public keys file
    if File.exist?("client/resources/capk.txt") then
        (bin/"emv").mkpath
        (bin/"emv").install "client/resources/capk.txt"
    end
```

**Comment by doegox** [comment]
no, it's found in place in resources

**Comment by iceman1001** [comment]
ok,  removed it
